version: '3.8'

services:
  dia-tts-mcp:
    build: .
    container_name: dia-tts-mcp
    environment:
      - HF_TOKEN=${HF_TOKEN:-}
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - TRANSFORMERS_CACHE=/app/cache/transformers
      - HF_HOME=/app/cache/huggingface
    volumes:
      - dia_tts_cache:/app/cache
      - dia_tts_temp:/tmp/dia_audio
    restart: unless-stopped
    mem_limit: 16g
    cpus: 8.0
    networks:
      - ollama-stack-network
    # MCP servers use stdio - no exposed ports needed
    # They integrate through the MCP proxy in the main stack
    healthcheck:
      test: ["CMD", "/app/health_check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  dia_tts_cache:
    name: dia_tts_cache
  dia_tts_temp:
    name: dia_tts_temp

networks:
  ollama-stack-network:
    external: true 