version: '3.8'

services:
  dia-tts-mcp:
    environment:
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0
      - TORCH_COMPILE=false
      - ACCELERATE_USE_MPS=true 